$(document).ready(function(){
    $("button:nth-of-type(1)").click(function(){
        $("img").attr("src","images/logo_01.jpg");
    });
    $("button:nth-of-type(2)").click(function(){
        $("img").attr("src","images/logo_02.jpg");
    });
    $("button:nth-of-type(3)").click(function(){
        $("img").attr("src","images/logo_03.jpg");
    });
});